import JSZip from 'jszip'
import { saveAs } from 'file-saver'

function sanitizeFileContent(content, fileName) {
  if (!content || typeof content !== 'string') return content

  let result = content

  const trimmed = result.trim()

  if ((trimmed.startsWith('{"') || trimmed.startsWith('{')) && trimmed.length > 20) {
    try {
      const possibleJSON = JSON.parse(trimmed)
      if (possibleJSON && typeof possibleJSON === 'object') {
        const extracted =
          possibleJSON.html ||
          possibleJSON.css ||
          possibleJSON.js ||
          possibleJSON.content ||
          possibleJSON.code ||
          content

        if (extracted !== content) {
          result = extracted
        }
      }
    } catch {
      // eslint-disable-line no-empty -- expected invalid JSON
      // 不是有效JSON
    }
  }

  const hasLiteralNewlines = /\\n/.test(result)
  const hasLiteralTabs = /\\t/.test(result)

  if (hasLiteralNewlines || hasLiteralTabs) {
    result = result
      .replace(/\\n/g, '\n')
      .replace(/\\t/g, '\t')
      .replace(/\\r/g, '\r')
      .replace(/\\"/g, '"')
  }

  return result
}

export function useCodePackager(options = {}) {
  const { defaultFileName = 'my-page', onProgress = () => {}, onComplete = () => {} } = options

  async function packAndDownload(files, projectName = null) {
    const zip = new JSZip()
    const name = projectName || defaultFileName

    try {
      for (const file of files) {
        const sanitizedContent = sanitizeFileContent(file.content, file.name)
        zip.file(file.name, sanitizedContent)
      }

      zip.file('README.md', generateReadme(files))

      if (!files.some((f) => f.name === 'package.json')) {
        zip.file(
          'package.json',
          JSON.stringify(
            {
              name: name.toLowerCase().replace(/\s+/g, '-'),
              version: '1.0.0',
              description: `Generated by AI-Code Studio`,
              scripts: {
                start: 'npx serve .',
              },
            },
            null,
            2,
          ),
        )
      }

      onProgress({ stage: 'compressing', progress: 50 })

      const content = await zip.generateAsync(
        {
          type: 'blob',
          compression: 'DEFLATE',
          compressionOptions: { level: 6 },
          comment: `Generated by AI-Code Studio on ${new Date().toLocaleString()}`,
        },
        (metadata) => {
          onProgress({
            stage: 'generating',
            progress: 50 + Math.round(metadata.percent * 0.5),
          })
        },
      )

      saveAs(content, `${name}.zip`)

      onComplete({ success: true, size: content.size })
      return { success: true, size: content.size }
    } catch (error) {
      console.error('打包失败:', error)
      throw error
    }
  }

  function generateReadme(files) {
    const hasHTML = files.some((f) => f.name.endsWith('.html'))
    const hasCSS = files.some((f) => f.name.endsWith('.css'))
    const hasJS = files.some((f) => f.name.endsWith('.js'))

    return `# ${name}

## 项目说明
此项目由 [AI-Code Studio](https://your-domain.com) 自动生成。

## 文件结构
\`\`\`
${files.map((f) => `├── ${f.name}`).join('\n')}
\`\`\`

## 使用方法

### 方式一：直接打开
${hasHTML ? '- 直接用浏览器打开 `index.html` 即可预览' : ''}

### 方式二：本地服务器
\`\`\`bash
npx serve .
# 或
python -m http.server 8080
\`\`\`

## 技术栈
- HTML5 ${hasCSS ? '+ CSS3' : ''} ${hasJS ? '+ JavaScript' : ''}
- 生成时间: ${new Date().toLocaleString()}
- 生成工具: AI-Code Studio v1.0

---
© ${new Date().getFullYear()} AI-Code Studio. All rights reserved.
`
  }

  async function exportSingleFile(files) {
    const htmlFile = files.find((f) => f.name.endsWith('.html'))
    if (!htmlFile) {
      throw new Error('未找到HTML文件')
    }

    const sanitizedContent = sanitizeFileContent(htmlFile.content, htmlFile.name)
    const blob = new Blob([sanitizedContent], { type: 'text/html;charset=UTF-8' })
    saveAs(blob, `${defaultFileName}.html`)
  }

  async function copyToClipboard(files) {
    const htmlFile = files.find((f) => f.name.endsWith('.html'))
    if (!htmlFile) return false

    const sanitizedContent = sanitizeFileContent(htmlFile.content, htmlFile.name)

    try {
      await navigator.clipboard.writeText(sanitizedContent)
      return true
    } catch {
      const textarea = document.createElement('textarea')
      textarea.value = sanitizedContent
      document.body.appendChild(textarea)
      textarea.select()
      document.execCommand('copy')
      document.body.removeChild(textarea)
      return true
    }
  }

  return {
    packAndDownload,
    exportSingleFile,
    copyToClipboard,
  }
}
